# Generated by Django 3.2.8 on 2021-10-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('payment_id', models.CharField(max_length=200)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
